export const ERROR_CODES = {
  AUTH: {
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED'
  },
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    PROFILE_EXISTS: 'PROFILE_EXISTS',
    INVALID_DISPLAY_NAME: 'INVALID_DISPLAY_NAME',
    INVALID_BIO: 'INVALID_BIO'
  },
  DEVICE: {
    NOT_FOUND: 'DEVICE_NOT_FOUND',
    MAX_DEVICES_REACHED: 'MAX_DEVICES_REACHED',
    ALREADY_REVOKED: 'ALREADY_REVOKED',
    NOT_OWNER: 'DEVICE_NOT_OWNER',
    INVALID_PLATFORM: 'INVALID_PLATFORM'
  },
  PAIRING: {
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_USED: 'SESSION_USED',
    SESSION_REVOKED: 'SESSION_REVOKED',
    ALREADY_PAIRED: 'ALREADY_PAIRED',
    NOT_INITIATOR: 'NOT_INITIATOR',
    INVALID_CODE: 'INVALID_CODE'
  },
  FILE: {
    NOT_FOUND: 'FILE_NOT_FOUND',
    TOO_LARGE: 'FILE_TOO_LARGE',
    INVALID_MIME_TYPE: 'INVALID_MIME_TYPE',
    INVALID_FILE_NAME: 'INVALID_FILE_NAME',
    NOT_OWNER: 'FILE_NOT_OWNER',
    TRANSFER_FAILED: 'TRANSFER_FAILED',
    UPLOAD_FAILED: 'UPLOAD_FAILED'
  },
  CHAT: {
    CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
    NOT_MEMBER: 'NOT_MEMBER',
    MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
    NOT_SENDER: 'NOT_SENDER',
    BLOCKED_USER: 'BLOCKED_USER'
  },
  CLIPBOARD: {
    NOT_ENABLED: 'CLIPBOARD_NOT_ENABLED',
    CONTENT_TOO_LARGE: 'CONTENT_TOO_LARGE',
    SENSITIVE_CONTENT_DETECTED: 'SENSITIVE_CONTENT_DETECTED'
  },
  SOCIAL: {
    POST_NOT_FOUND: 'POST_NOT_FOUND',
    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
    NOT_AUTHOR: 'NOT_AUTHOR',
    ALREADY_LIKED: 'ALREADY_LIKED',
    POST_REMOVED: 'POST_REMOVED'
  },
  REPORT: {
    ALREADY_REPORTED: 'ALREADY_REPORTED',
    SELF_REPORT: 'SELF_REPORT',
    INVALID_REASON: 'INVALID_REASON'
  },
  GENERAL: {
    RATE_LIMITED: 'RATE_LIMITED',
    INVALID_INPUT: 'INVALID_INPUT',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    PERMISSION_DENIED: 'PERMISSION_DENIED'
  }
} as const;

export type ErrorCode = 
  | typeof ERROR_CODES.AUTH[keyof typeof ERROR_CODES.AUTH]
  | typeof ERROR_CODES.USER[keyof typeof ERROR_CODES.USER]
  | typeof ERROR_CODES.DEVICE[keyof typeof ERROR_CODES.DEVICE]
  | typeof ERROR_CODES.PAIRING[keyof typeof ERROR_CODES.PAIRING]
  | typeof ERROR_CODES.FILE[keyof typeof ERROR_CODES.FILE]
  | typeof ERROR_CODES.CHAT[keyof typeof ERROR_CODES.CHAT]
  | typeof ERROR_CODES.CLIPBOARD[keyof typeof ERROR_CODES.CLIPBOARD]
  | typeof ERROR_CODES.SOCIAL[keyof typeof ERROR_CODES.SOCIAL]
  | typeof ERROR_CODES.REPORT[keyof typeof ERROR_CODES.REPORT]
  | typeof ERROR_CODES.GENERAL[keyof typeof ERROR_CODES.GENERAL];

export function createAppError(code: string, message: string, details?: unknown) {
  return { code, message, details };
}
